---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shibliho/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/css
    - /bin/mkdir -p $DEPLOYPATH/js
    - /bin/cp css/styles.css $DEPLOYPATH/css/
    - /bin/cp js/script.js $DEPLOYPATH/js/